"use client";

import IconifyIcon from "./IconifyIcon";
import { motion } from "framer-motion";
import Link from "next/link";

const features = [
    {
        icon: "solar:magnifer-linear",
        title: "AI Career Discovery",
        description: "Find the career path that perfectly matches your interests, academic background, and strengths.",
        color: "bg-blue-500/10 text-blue-500",
        href: "/career-discovery",
    },
    {
        icon: "solar:routing-2-linear",
        title: "Career Roadmap",
        description: "Get a step-by-step actionable plan guiding you from a confused student to a job-ready professional.",
        color: "bg-primary/10 text-primary",
    },
    {
        icon: "solar:document-text-linear",
        title: "ATS Resume Builder",
        description: "Create optimized resumes formatted exactly how modern Applicant Tracking Systems expect them.",
        color: "bg-emerald-500/10 text-emerald-500",
    },
    {
        icon: "solar:scanner-linear",
        title: "Skill Gap Analyzer",
        description: "Our AI identifies the exact technical and soft skills you are missing for your target role.",
        color: "bg-amber-500/10 text-amber-500",
    },
    {
        icon: "solar:microphone-linear",
        title: "AI Interview Prep",
        description: "Practice with dynamic, structured interview questions generated by AI based on real company data.",
        color: "bg-indigo-500/10 text-indigo-500",
        hasPulse: true,
        href: "/ai-interview",
    },
    {
        icon: "solar:pie-chart-linear",
        title: "Progress Dashboard",
        description: "Track your overall readiness score and see how prepared you are to enter the industry.",
        color: "bg-rose-500/10 text-rose-500",
        href: "/dashboard",
    },
];

export default function PlatformSection() {
    return (
        <section id="platform" className="py-32 bg-white relative overflow-hidden border-b border-slate-100">
            {/* Background Accent */}
            <div className="absolute bottom-0 left-0 w-[40rem] h-[40rem] bg-primary/5 blur-[120px] rounded-full pointer-events-none"></div>

            <div className="max-w-7xl mx-auto px-6">
                <div className="mb-20">
                    <motion.div 
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        className="text-primary text-sm font-medium tracking-[0.2em] uppercase mb-6 flex items-center gap-4"
                    >
                        <span className="w-12 h-px bg-primary"></span> The Platform
                    </motion.div>
                    
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-end">
                        <motion.h2 
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: 0.2 }}
                            className="text-4xl md:text-6xl font-medium font-heading tracking-tighter leading-tight text-slate-900"
                        >
                            Infrastructure for <br />
                            <span className="text-primary">Career Excellence.</span>
                        </motion.h2>
                        
                        <motion.p 
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: 0.3 }}
                            className="text-lg font-light text-slate-500 max-w-lg leading-relaxed"
                        >
                            A comprehensive ecosystem designed to transform potential into performance, powered by industry-grade AI intelligence.
                        </motion.p>
                    </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-px bg-slate-200 border border-slate-200 rounded-[2.5rem] overflow-hidden shadow-sm">
                    {features.map((feature, i) => (
                        <motion.div 
                            key={i}
                            initial={{ opacity: 0 }}
                            whileInView={{ opacity: 1 }}
                            viewport={{ once: true }}
                            transition={{ delay: 0.1 * i }}
                            className="group relative p-12 bg-white hover:bg-slate-50 transition-all duration-500"
                        >
                            <div className="relative z-10 flex flex-col h-full">
                                <div className={`w-14 h-14 rounded-2xl flex items-center justify-center mb-8 ${feature.color} group-hover:scale-110 transition-transform duration-500 relative`}>
                                    {feature.hasPulse && (
                                        <span className="absolute -top-1 -right-1 flex h-3 w-3">
                                            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary opacity-75"></span>
                                            <span className="relative inline-flex rounded-full h-3 w-3 bg-primary"></span>
                                        </span>
                                    )}
                                    <IconifyIcon icon={feature.icon} className="text-2xl" />
                                </div>
                                
                                <h3 className="text-xl font-semibold font-heading text-slate-900 mb-4 tracking-tight">
                                    {feature.title}
                                </h3>
                                
                                <p className="text-slate-500 font-light leading-relaxed mb-8 flex-grow">
                                    {feature.description}
                                </p>

                                {feature.href ? (
                                    <Link href={feature.href} className="inline-flex items-center gap-2 text-primary text-xs font-semibold tracking-widest uppercase group-hover:gap-3 transition-all">
                                        Explore <IconifyIcon icon="solar:arrow-right-linear" />
                                    </Link>
                                ) : (
                                    <span className="text-slate-300 text-[10px] font-medium tracking-[0.2em] uppercase">Coming Soon</span>
                                )}
                            </div>
                        </motion.div>
                    ))}
                </div>
            </div>
        </section>
    );
}
